server:
  port: 9100

spring:
  datasource:
    url: jdbc:mysql://localhost/wanna-help?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

newpassword:
  HoursToExpire: 24