server:
  port: 9100

spring:
  datasource:
    url: jdbc:mysql://localhost/wanna-help?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

newpassword:
  HoursToExpire: 24

email_password_reset_content: |
  <html>
    <head>
      <style>
        a.button {
          display: inline-block;
          padding: 10px 20px;
          margin-right: 10px;
          text-decoration: none;
          border-radius: 20px;
          background-color: #4285f4;
          color: #ffffff;
        }
      </style>
    </head>
    <body>
      <p>Dear User,</p>
      <p>Please click the button below to reset your password:</p>
      <a href="{{ link }}" class="button">Password reset</a>
    </body>
  </html>


email_accept_decline_content: |
  <html>
    <head>
      <style>
        a.button {
          display: inline-block;
          padding: 10px 20px;
          margin-right: 10px;
          text-decoration: none;
          border-radius: 20px;
        }
      </style>
    </head>
    <body>
      <p>Dear Volunteer,</p>
      <p>You have an invitation from {{ helpSeekerName }} to participate in the new activity:</p>
      <pre>{{ activityDetails }}</pre>
      <a href="{{ acceptLink }}" class="button" style="background-color:#00cc00; color:#ffffff;">Accept</a>
      <a href="{{ declineLink }}" class="button" style="background-color:#ff0000; color:#ffffff;">Decline</a>
    </body>
  </html>



email_content: |
  <html>
    <head>
      <style>
        a.button {
          display: inline-block;
          padding: 10px 20px;
          margin-right: 10px;
          text-decoration: none;
          border-radius: 20px;
        }
      </style>
    </head>
    <body>
      <p>Dear Volunteer,</p>
      <p>You have an invitation from {{ helpSeekerName }} to participate in the new activity:</p>
      <pre>{{ activityDetails }}</pre>
      <a href="{{ acceptLink }}" class="button" style="background-color:#00cc00; color:#ffffff;">Accept</a>
      <a href="{{ declineLink }}" class="button" style="background-color:#ff0000; color:#ffffff;">Decline</a>
    </body>
  </html>